### ISSUE TITLE
Some ideas... v2.0 xD

### ISSUE THREAD

**Issue by Cubansephiroth** [fixcore/BlizzCMS#38]
Some other ideas that might be useful to implement...

[x] Why keep 2 projects? one for source and another one for DB updates? it can be a little messy :(
- It will be better to set the name of SQL updates like year_month_day.sql
- An option to enable/disable modules in ACP will be better than 0-1 in fx_modules
- An option to enable or disable account locked in UCP (the user can only log in from an specific ip address) with security question confirmation ofc.

Thats all for today, keep the great work and thanks for this amazing product.

**Comment by fixcore** [comment]
Why keep 2 projects? one for source and another one for DB updates? it can be a little messy :(
An option to enable/disable modules in ACP will be better than 0-1 in fx_modules

Because we have constants updates with the database, also i change variable types etc.. so i can't 


An option to enable or disable account locked in UCP (the user can only log in from an specific ip address) with security question confirmation ofc.

Good idea but, if i use vpn?

_Thanks for your ideas_
